apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: keystone
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: keystone
    spec:
      volumes:
        - name: preload-config
          configMap:
            name: keystone-preload
            items:
              - key: preload.yml
                path: preload.yml
      containers:
        - name: keystone
          image: monasca/keystone:1.0.0
          env:
            - name: KEYSTONE_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KEYSTONE_PASSWORD
              value: secretadmin
            - name: KEYSTONE_DATABASE_BACKEND
              value: mysql
            - name: KEYSTONE_MYSQL_HOST
              value: keystone-mysql
            - name: KEYSTONE_MYSQL_USER
              value: keystone
            - name: KEYSTONE_MYSQL_PASSWORD
              value: keystone
            - name: KEYSTONE_MYSQL_DATABASE
              value: keystone
          ports:
            - name: http
              containerPort: 5000
            - name: admin
              containerPort: 35357
          volumeMounts:
            - name: preload-config
              mountPath: /preload.yml
              subPath: preload.yml
---
apiVersion: v1
kind: Service
metadata:
  name: keystone
  namespace: monitoring
  labels:
    app: keystone
spec:
  ports:
    - name: http
      port: 5000
      targetPort: http
    - name: admin
      port: 35357
      targetPort: admin
  selector:
    app: keystone
