repository: fest/log-api
variants:
  - tag: pike
    aliases:
      - :pike-{date}-{time}
    args:
      LOG_API_BRANCH: stable/pike
      CONSTRAINTS_BRANCH: stable/pike
      PYTHON_VERSION: '2'
      TIMESTAMP_SLUG: 20170809-155207
