repository: fest/log-api
variants:
  - tag: pike-latest
    aliases:
      - :pike-{date}-{time}
    args:
      LOG_API_BRANCH: stable/pike
      CONSTRAINTS_BRANCH: stable/pike
      PYTHON_VERSION: '2'
      TIMESTAMP_SLUG: pike-latest
 
