repository: monasca/log-api
variants:
  - tag: master
    aliases:
      - :master-{date}-{time}
    args:
      LOG_API_BRANCH: master
      CONSTRAINTS_BRANCH: master

  - tag: 2.2.1
    aliases:
      - :latest
      - :2.2
      - :2
    args:
      LOG_API_BRANCH: 2.2.1
      CONSTRAINTS_BRANCH: master
  - tag: 2.1.0
    aliases:
      - :2.1
    args:
      LOG_API_BRANCH: 2.1.0
      CONSTRAINTS_BRANCH: master
  - tag: 2.0.0
    aliases:
      - :2.0
    args:
      LOG_API_BRANCH: 2.0.0
      CONSTRAINTS_BRANCH: master

  - tag: ocata
    args:
      LOG_API_BRANCH: stable/ocata
      CONSTRAINTS_BRANCH: stable/ocata
  - tag: 1.4.1
    aliases:
      - :1.4
      - :1
    args:
      LOG_API_BRANCH: 1.4.1
      CONSTRAINTS_BRANCH: stable/ocata

