sudo: required
services:
  - docker
language: python

env:
  - IGNORE_DOCKER_VERSION=true

before_install:
  - pip install git+https://github.com/timothyb89/dbuild.git
  - sed -i "s/version: '3'/version: '2'/" docker-compose.yml

script:
  - python ci.py
