####################################################
# Make sure that Keystone is alread running
# !!!! Configure MON_KEYSTONE_URL in .env !!!!
####################################################
version: '2'
services:

  log-metrics:
    image: fest/log-metrics:${MON_LOG_METRICS_VERSION}
    environment:
      LOGSTASH_FIELDS: "service=monasca-log-metrics"
    depends_on:
      - kafka
      - zookeeper
      - log-transformer

  log-persister:
    image: fest/log-persister:${MON_LOG_PERSISTER_VERSION}
    environment:
      LOGSTASH_FIELDS: "service=monasca-log-persister"
    depends_on:
      - kafka
      - zookeeper
      - elasticsearch
      - log-transformer

  log-transformer:
    image: fest/log-transformer:${MON_LOG_TRANSFORMER_VERSION}
    environment:
      LOGSTASH_FIELDS: "service=monasca-log-transformer"
    depends_on:
      - kafka
      - zookeeper
      - log-api

  elasticsearch:
    image: fest/elasticsearch:${ELASTICSEARCH_VERSION}

    environment:
      - LOGSTASH_FIELDS="service=elasticsearch"
    volumes:
      - /usr/share/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  elasticsearch-init:
    image: fest/elasticsearch-init:${MON_ELASTICSEARCH_INIT_VERSION}
    environment:
      LOGSTASH_FIELDS: "service=elasticsearch-init"
    volumes:
      - ./elasticsearch-templates/logs.template:/templates/logs.json
    depends_on:
      - elasticsearch

  kafka-log-init:
    image: fest/kafka-init:${MON_KAFKA_INIT_VERSION}
    environment:
      KAFKA_TOPIC_CONFIG: segment.ms=900000 # 15m
      KAFKA_CREATE_TOPICS: "\
        log:4:1,\
        log-transformed:4:1"
      LOGSTASH_FIELDS: "service=kafka-log-init"
    depends_on:
      - kafka

  kibana:
    image: fest/kibana:${MON_KIBANA_VERSION}
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_PINGTIMEOUT: 1000
      LOGSTASH_FIELDS: "service=kibana"
      KEYSTONE_URI: ${MON_KEYSTONE_URL}
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

  log-api:
    image: fest/log-api:${MON_LOG_API_VERSION}
    environment:
      LOGSPOUT: ignore
      LOGSTASH_FIELDS: "service=monasca-log-api"
      #TODO: keystone URI should be sufficient!?
      # use port 35357 for KEYSTONE_IDENTITY_URI? are really both URIs needed?
      KEYSTONE_IDENTITY_URI: ${MON_KEYSTONE_URL}
      KEYSTONE_AUTH_URI: ${MON_KEYSTONE_URL}
      KEYSTONE_ADMIN_USER: admin
      KEYSTONE_ADMIN_PASSWORD: secretadmin
      #KEYSTONE_ADMIN_TENANT: admin
      #KEYSTONE_ADMIN_DOMAIN: default
    depends_on:
      - zookeeper
      - kafka
      - memcached
    ports:
      - "5607:5607"

  log-agent:
    image: fest/log-agent:${MON_LOG_AGENT_VERSION}
    environment:
      LOGSPOUT: ignore
      LOGSTASH_FIELDS: "service=monasca-log-agent"
      #TODO: adapt readme! not tested yet!
      OS_AUTH_URL: ${MON_KEYSTONE_URL}/v3
      OS_USERNAME: monasca-agent
      OS_PASSWORD: password
      OS_PROJECT_NAME: mini-mon
      #OS_USER_DOMAIN_NAME: Default
      #OS_PROJECT_DOMAIN_NAME: Default
    depends_on:
      - log-api
    ports:
      - "5610:5610"

  logspout:
    image: fest/logspout:${MON_LOGSPOUT_VERSION}
    environment:
      LOGSPOUT: ignore
      LOGSTASH_FIELDS: "service=logspout"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
        - log-agent
