- name: Enables the keystone docker container
  hosts: devstack
  gather_facts: no
  vars:
    # I didn't want to set the default everywhere so I set a variable with a variable. Common options are stopped, absent
    state: "{{ action | default('running') }}"
    docker_url: "unix://var/run/docker.sock"
  tasks:
  - name: keystone
    docker:
        image: monasca/keystone
        name: keystone
    tags:
      - keystone
