- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    # I didn't want to set the default everywhere so I set a variable with a variable. Common options are stopped, absent
    state: "{{ action | default('present') }}"
  tasks:
  - name: Start influxdb
    docker:
        docker_url: tcp://127.0.0.1:2375
        image: monasca/influxdb 
        name: influxdb
        state: "{{ state }}"
        ports:
          - "8083:8083"
          - "8084:8084"
          - "8086:8086"
  - name: Start mysql (percona xtraDB cluster)
    docker:
        docker_url: tcp://127.0.0.1:2375
        image: monasca/mysql
        name: mysql
        state: "{{ state }}"
        ports:
          - "3306:3306"
  - name: start zookeeper
    docker:
        docker_url: tcp://127.0.0.1:2375
        image: jplock/zookeeper
        name: zookeeper
        state: "{{ state }}"
  - name: start kafka
    docker:
        docker_url: tcp://127.0.0.1:2375
        image: monasca/kafka
        name: kafka
        state: "{{ state }}"
        links:
          - zookeeper:zookeeper
  - name: start persister
    docker:
        docker_url: tcp://127.0.0.1:2375
        image: monasca/persister
        name: persister
        state: "{{ state }}"
        links:
          - kafka:kafka
          - influxdb:influxdb
          - zookeeper:zookeeper
  - name: start notification enging
    docker:
        docker_url: tcp://127.0.0.1:2375
        image: monasca/notification
        name: notification
        state: "{{ state }}"
        links:
          - kafka:kafka
          - mysql:mysql
          - zookeeper:zookeeper

# Old fig style boxes yet to be converted for ansible
#thresh:
#  image: monasca/thresh
#  links:
#    - kafka
#    - mysql
##    - zookeeper
#api:
#  image: monasca/api
#  ports: "8080:8080"
#  links: 
#    - devstack
#    - influxdb
#    - kafka
#    - mysql
#    - zookeeper


#devstack? Done by itself or with the ui on it?
#ui:
#  image: monasca/ui
#  ports: "80:80"
#  links: 
#    - devstack
#    - api
#agent:
#  image: monasca/agent
#  links: 
#    - devstack
#    - api
