- name: Enables the docker containers needed for a stand alone Monasca, only keystone is required beyond this set
  hosts: mini-mon
  gather_facts: no
  vars:
    # I didn't want to set the default everywhere so I set a variable with a variable. Common options are stopped, absent
    state: "{{ action | default('running') }}"
  tasks:
  - name: influxdb
    docker:
        image: monasca/influxdb 
        name: influxdb
        state: "{{state}}"
        ports:
          - "8083:8083"
          - "8084:8084"
          - "8086:8086"
    tags:
      - influxdb
  - name: mysql (percona xtraDB cluster)
    docker:
        image: monasca/mysql
        name: mysql
        state: "{{state}}"
        ports:
          - "3306:3306"
    tags:
      - mysql
  - name: zookeeper
    docker:
        image: monasca/zookeeper
        name: zookeeper
        state: "{{state}}"
    tags:
      - zookeeper
  - name: kafka
    docker:
        image: monasca/kafka
        name: kafka
        hostname: kafka  # This is important so that kafka registers itself properly in zookeeper
        state: "{{state}}"
        links:
          - zookeeper:zookeeper
    tags:
      - kafka
  - name: persister
    docker:
        image: monasca/persister
        name: persister
        state: "{{state}}"
        links:
          - kafka:kafka
          - influxdb:influxdb
          - zookeeper:zookeeper
    tags:
      - persister
  - name: threshold engine
    docker:
        image: monasca/thresh
        name: thresh
        hostname: thresh
        state: "{{state}}"
        links:
          - kafka:kafka
          - mysql:mysql
          - zookeeper:zookeeper
    tags:
      - thresh
  - name: notification engine
    docker:
        image: monasca/notification
        name: notification
        state: "{{state}}"
        links:
          - kafka:kafka
          - mysql:mysql
          - zookeeper:zookeeper
    tags:
      - notification
  - name: api
    docker:
        image: monasca/api
        name: api
        ports:
          - "8080:8080"
        state: "{{state}}"
        links:
          - keystone:keystone
          - kafka:kafka
          - influxdb:influxdb
          - mysql:mysql
          - zookeeper:zookeeper
    tags:
      - api
  - name: agent
    docker:
        image: monasca/agent
        name: agent
        tty: True
        stdin_open: True
        state: "{{state}}"
        links:
          - api:api
          - keystone:keystone
    tags:
      - agent
#  - name: ui
#    docker:
#        image: monasca/ui
#        name: ui
#        links:
#          - api:api
#          - keystone:keystone
