- hosts: localhost
  connection: local
  tasks:
  - name: Start mini-mon
    docker:
        docker_url: tcp://127.0.0.1:2375
        image: monasca/influxdb 
        name: influxdb
        ports:
          - "8083:8083"
          - "8084:8084"
          - "8086:8086"
  - name: start zookeeper
    docker:
        docker_url: tcp://127.0.0.1:2375
        image: jplock/zookeeper
        name: zookeeper
  - name: start kafka
    docker:
        docker_url: tcp://127.0.0.1:2375
        image: monasca/kafka
        name: kafka
        links:
          - zookeeper:zookeeper

# Old fig style boxes yet to be converted for ansible
#mysql:
#  image: monasca/mysql
#notification:
#  image: monasca/notification
#  links:
#    - kafka
#    - mysql
#    - zookeeper
#persister:
#  image: monasca/persister
#  links:
#    - influxdb
#    - kafka
#    - mysql
#    - zookeeper
#thresh:
#  image: monasca/thresh
#  links:
#    - kafka
#    - mysql
##    - zookeeper
#api:
#  image: monasca/api
#  ports: "8080:8080"
#  links: 
#    - devstack
#    - influxdb
#    - kafka
#    - mysql
#    - zookeeper

#ui:
#  image: monasca/ui
#  ports: "80:80"
#  links: 
#    - devstack
#    - api
#agent:
#  image: monasca/agent
#  links: 
#    - devstack
#    - api
