- name: Enables the docker containers needed for a stand alone Monasca, aka mini-mon. This setup has each service in its own container.
  hosts: mini-mon
  sudo: yes
  gather_facts: no
  vars:
    # I didn't want to set the default everywhere so I set a variable with a variable. Common options are stopped, absent
    state: "{{ action | default('running') }}"
  tasks:
  - name: influxdb
    docker:
        image: monasca/influxdb:{{ influxdb_tag | default('latest') }}
        name: influxdb
        state: "{{state}}"
        ports:
          - "8083:8083"
          - "8084:8084"
          - "8086:8086"
    tags:
      - influxdb
  - name: mysql (percona xtraDB cluster)
    docker:
        image: monasca/mysql:{{ mysql_tag | default('latest') }}
        name: mysql
        state: "{{state}}"
        ports:
          - "3306:3306"
    tags:
      - mysql
  - name: zookeeper
    docker:
        image: monasca/zookeeper:{{ zookeeper_tag | default('latest') }}
        name: zookeeper
        state: "{{state}}"
    tags:
      - zookeeper
  - name: kafka
    docker:
        image: monasca/kafka:{{ kafka_tag | default('latest') }}
        name: kafka
        hostname: kafka  # This is important so that kafka registers itself properly in zookeeper
        state: "{{state}}"
        links:
          - zookeeper:zookeeper
    tags:
      - kafka
  - name: persister
    docker:
        image: monasca/persister:{{ persister_tag | default('latest') }}
        name: persister
        state: "{{state}}"
        links:
          - kafka:kafka
          - influxdb:influxdb
          - zookeeper:zookeeper
    tags:
      - persister
  - name: threshold
    docker:
        image: monasca/thresh:{{ threshold_tag | default('latest') }}
        name: thresh
        hostname: thresh
        state: "{{state}}"
        links:
          - kafka:kafka
          - mysql:mysql
          - zookeeper:zookeeper
    tags:
      - thresh
  - name: notification
    docker:
        image: monasca/notification:{{ notification_tag | default('latest') }}
        name: notification
        state: "{{state}}"
        links:
          - kafka:kafka
          - mysql:mysql
          - zookeeper:zookeeper
    tags:
      - notification
  - name: api
    docker:
        image: monasca/api:{{ api_tag | default('latest') }}
        name: api
        ports:
          - "8080:8080"
        state: "{{state}}"
        links:
          - kafka:kafka
          - influxdb:influxdb
          - mysql:mysql
          - zookeeper:zookeeper
          - openstack:keystone
    tags:
      - api
  - name: agent
    docker:
        image: monasca/agent:{{ agent_tag | default('latest') }}
        name: agent
        tty: True
        stdin_open: True
        state: "{{state}}"
        links:
          - api:api
          - openstack:keystone
    tags:
      - agent
  - name: Openstack
    docker:
        image: monasca/openstack:{{ openstack_tag | default('latest') }}
        name: openstack
        links:
          - api:api
