- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    # I didn't want to set the default everywhere so I set a variable with a variable. Common options are stopped, absent
    state: "{{ action | default('present') }}"
    docker_url: "{{ lookup('env','DOCKER_HOST') | default('unix://var/run/docker.sock') }}"
  tasks:
  - name: influxdb
    docker:
        docker_url: "{{ docker_url }}"
        image: monasca/influxdb 
        name: influxdb
        state: "{{ state }}"
        ports:
          - "8083:8083"
          - "8084:8084"
          - "8086:8086"
  - name: mysql (percona xtraDB cluster)
    docker:
        docker_url: "{{ docker_url }}"
        image: monasca/mysql
        name: mysql
        state: "{{ state }}"
        ports:
          - "3306:3306"
  - name: zookeeper
    docker:
        docker_url: "{{ docker_url }}"
        image: jplock/zookeeper
        name: zookeeper
        state: "{{ state }}"
  - name: kafka
    docker:
        docker_url: "{{ docker_url }}"
        image: monasca/kafka
        name: kafka
        hostname: kafka  # This is important so that kafka registers itself properly in zookeeper
        state: "{{ state }}"
        links:
          - zookeeper:zookeeper
  - name: persister
    docker:
        docker_url: "{{ docker_url }}"
        image: monasca/persister
        name: persister
        state: "{{ state }}"
        links:
          - kafka:kafka
          - influxdb:influxdb
          - zookeeper:zookeeper
#  - name: threshold engine
#    docker:
#        docker_url: "{{ docker_url }}"
#        image: monasca/thresh
#        name: thresh
#        state: "{{ state }}"
#        links:
#          - kafka:kafka
#          - mysql:mysql
#          - zookeeper:zookeeper
  - name: notification engine
    docker:
        docker_url: "{{ docker_url }}"
        image: monasca/notification
        name: notification
        state: "{{ state }}"
        links:
          - kafka:kafka
          - mysql:mysql
          - zookeeper:zookeeper

# Old fig style boxes yet to be converted for ansible
#api:
#  image: monasca/api
#  ports: "8080:8080"
#  links: 
#    - devstack
#    - influxdb
#    - kafka
#    - mysql
#    - zookeeper


#devstack? Done by itself or with the ui on it?
#ui:
#  image: monasca/ui
#  ports: "80:80"
#  links: 
#    - devstack
#    - api
#agent:
#  image: monasca/agent
#  links: 
#    - devstack
#    - api
