- hosts: mini-mon
  gather_facts: no
  vars:
    # I didn't want to set the default everywhere so I set a variable with a variable. Common options are stopped, absent
    state: "{{ action | default('running') }}"
    docker_url: "unix://var/run/docker.sock"
  tasks:
  - name: influxdb
    docker:
        image: monasca/influxdb 
        name: influxdb
        ports:
          - "8083:8083"
          - "8084:8084"
          - "8086:8086"
  - name: mysql (percona xtraDB cluster)
    docker:
        image: monasca/mysql
        name: mysql
        ports:
          - "3306:3306"
  - name: zookeeper
    docker:
        image: jplock/zookeeper
        name: zookeeper
  - name: kafka
    docker:
        image: monasca/kafka
        name: kafka
        hostname: kafka  # This is important so that kafka registers itself properly in zookeeper
        links:
          - zookeeper:zookeeper
  - name: keystone
    docker:
        image: monasca/keystone
        name: keystone
  - name: persister
    docker:
        image: monasca/persister
        name: persister
        links:
          - kafka:kafka
          - influxdb:influxdb
          - zookeeper:zookeeper
  - name: threshold engine
    docker:
        image: monasca/thresh
        name: thresh
        hostname: thresh
        links:
          - kafka:kafka
          - mysql:mysql
          - zookeeper:zookeeper
  - name: notification engine
    docker:
        image: monasca/notification
        name: notification
        links:
          - kafka:kafka
          - mysql:mysql
          - zookeeper:zookeeper
  - name: api
    docker:
        image: monasca/api
        name: api
        ports:
          - "8080:8080"
        links:
          - keystone:keystone
          - kafka:kafka
          - influxdb:influxdb
          - mysql:mysql
          - zookeeper:zookeeper
  - name: agent
    docker:
        image: monasca/agent
        name: agent
        tty: True
        stdin_open: True
        links:
          - api:api
          - keystone:keystone
#  - name: ui
#    docker:
#        image: monasca/ui
#        name: ui
#        links:
#          - api:api
#          - keystone:keystone
