apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: monasca/kafka:0.8.1.1-2.9.2
          ports:
            - name: kafka
              containerPort: 9092
          volumeMounts:
            - name: kafka
              mountPath: /data
          env:
            - name: ZOOKEEPER_CONNECTION_STRING
              value: zookeeper:2181
            - name: KAFKA_ADVERTISED_HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KAFKA_DELETE_TOPIC_ENABLE
              value: "true"
        - name: kafka-exporter
          image: rbrndt/kafka-prometheus:latest
          ports:
            - name: prometheus
              containerPort: 7204
          volumeMounts:
            - name: kafka-exporter
              mountPath: /prometheus-config
      volumes:
        - name: kafka
          persistentVolumeClaim:
            claimName: monitoring-kafka
        - name: kafka-exporter
          configMap:
            name: kafka.prometheus
