apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: monasca/kafka:0.9.0.1-2.11
          ports:
            - name: kafka
              containerPort: 9092
          volumeMounts:
            - name: kafka
              mountPath: /data
          env:
            - name: ZOOKEEPER_CONNECTION_STRING
              value: zookeeper:2181
            - name: KAFKA_DELETE_TOPIC_ENABLE
              value: "true"
            - name: KAFKA_AUTO_CREATE_TOPICS
              value: "false"
            - name: KAFKA_JMX
              value: "true"
            - name: KAFKA_CREATE_TOPICS
              value: "\
                metrics:64:1,alarm-state-transitions:12:1,\
                alarm-notifications:12:1,retry-notifications:3:1,\
                events:12:1,60-seconds-notifications:3:1"
        - name: kafka-exporter
          image: rbrndt/kafka-prometheus:latest
          ports:
            - name: prometheus
              containerPort: 7204
          volumeMounts:
            - name: kafka-exporter
              mountPath: /prometheus-config
      volumes:
        - name: kafka
          persistentVolumeClaim:
            claimName: monitoring-kafka
        - name: kafka-exporter
          configMap:
            name: kafka.prometheus
