apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: monitoring
  labels:
    app: kafka
spec:
  type: NodePort
  ports:
    - name: kafka
      port: 9092
      targetPort: kafka
  selector:
    app: kafka
