---
apiVersion: v1
kind: ReplicationController
metadata:
  name: storm-supervisor
  namespace: monitoring
spec:
  replicas: 1
  selector:
    app: storm-supervisor
  template:
    metadata:
      labels:
        app: storm-supervisor
    spec:
      containers:
      - name: monasca-thresh
        image: timothyb89/storm:1.0.2.4
        args: ["storm", "supervisor"]
        volumeMounts:
        - name: config-volume
          mountPath: /config
      volumes:
      - name: config-volume
        configMap:
          name: monasca-thresh.config

