---
apiVersion: v1
kind: Service
metadata:
  name: storm-nimbus
  namespace: monitoring
  labels:
    app: storm-nimbus
spec:
  ports:
  - name: nimbus
    port: 6627
  selector:
    app: storm-nimbus
