- name: Installs mysql
  hosts: localhost
  sudo: yes
  roles:
    - {role: percona, mysql_root_password: password, percona_package: percona-xtradb-cluster-56, tags: [mysql, percona]}

- name: Set up mysql schema
  hosts: localhost
  sudo: yes
  vars:
    mysql_admin: root
    mysql_admin_password: password
    kafka_topics_enabled: false
    influxdb_schema_enabled: false
    mysql_schema_enabled: true
    winchester_schema_enabled: false
    mysql_users:
      notification: password
      monapi: password
      thresh: password
  roles:
    - {role: monasca-schema, tags: [schema]}
