---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: monitoring
  labels:
    app: mysql
spec:
  type: NodePort
  ports:
  - name: client
    port: 3306
    protocol: TCP
  selector:
    app: mysql

