apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-init-job
  namespace: monitoring
spec:
  template:
    metadata:
      labels:
        app: mysql-init-job
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mysql-init-job
          image: monasca/mysql-init:1.1.0
          env:
            - name: MYSQL_INIT_DISABLE_REMOTE_ROOT
              value: "true"
            - name: MYSQL_INIT_RANDOM_PASSWORD
              value: "true"
