- name: Install Monasca persister
  hosts: localhost
  sudo: yes
  vars:
    kafka_hosts: kafka:9092
    influxdb_host: influxdb
    influxdb_url: http://influxdb:8086
    influxdb_user: mon_persister
    influxdb_password: password
    zookeeper_hosts: zookeeper:2181
  roles:
    - {role: monasca-persister, tags: [persister]}
