---
# Some of this comes from https://github.com/dguerri/openstack-horizon
- name: Install horizon application and dependencies
  apt: name="{{ item }}" state=present
  with_items:
    - apache2
    - memcached
    - libapache2-mod-wsgi
    - openstack-dashboard

- name: Remove Ubuntu theme
  apt: name="{{ item }}" state=absent purge=yes
  with_items:
    - openstack-dashboard-ubuntu-theme

- name: Configure keystone in horizon
  lineinfile: dest=/etc/openstack-dashboard/local_settings.py
              regexp=^OPENSTACK_HOST
              line="OPENSTACK_HOST = '127.0.0.1'"

- name: Configure static secret_key
  lineinfile: dest=/etc/openstack-dashboard/local_settings.py
              regexp=^SECRET_KEY
              line="SECRET_KEY = '{{horizon_secret_key}}'"

- name: Disable default apache config
  file: path=/etc/apache2/sites-enabled/000-default.conf state=absent

- name: Setup root to be horizon
  lineinfile: dest=/etc/apache2/conf-enabled/openstack-dashboard.conf
              regexp=^WSGIScriptAlias
              line="WSGIScriptAlias / /usr/share/openstack-dashboard/openstack_dashboard/wsgi/django.wsgi"

- name: Run python manage.py compress for the dashboard
  command: python /usr/share/openstack-dashboard/manage.py compress
