apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
  namespace: monitoring
subsets:
  - addresses:
      - ip: 10.243.82.132
    ports:
      - port: 1
  - addresses:
      - ip: 10.243.82.133
    ports:
      - port: 1
  - addresses:
      - ip: 10.243.82.134
    ports:
      - port: 1
  - addresses:
      - ip: 10.243.82.135
    ports:
      - port: 1
---
kind: Service
apiVersion: v1
metadata:
  name: glusterfs-cluster
  namespace: monitoring
spec:
  ports:
    - port: 1
