apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: monasca/kafka:0.9.0.1-2.11
          ports:
            - name: kafka
              containerPort: 9092
          env:
            - name: ZOOKEEPER_CONNECTION_STRING
              value: zookeeper:2181
            - name: KAFKA_AUTO_CREATE_TOPICS
              value: "false"
            - name: KAFKA_DELETE_TOPIC_ENABLE
              value: "true"
            - name: KAFKA_CREATE_TOPICS
              value: "\
                metrics:64:1,alarm-state-transitions:12:1,\
                alarm-notifications:12:1,retry-notifications:3:1,\
                events:12:1,60-seconds-notifications:3:1"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: monitoring
  labels:
    app: kafka
spec:
  type: NodePort
  ports:
    - name: kafka
      port: 9092
      targetPort: kafka
  selector:
    app: kafka
