---
apiVersion: v1
kind: ReplicationController
metadata:
  name: influx
  namespace: monitoring
spec:
  replicas: 1
  selector:
    app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: monitoring-influx
        - name: config
          configMap:
            name: influxdb-1.0.0.conf
      containers:
        - name: influxdb
          image: influxdb:1.1
          ports:
            - containerPort: 8086
              name: http
            - containerPort: 8083
              name: admin
          volumeMounts:
            - name: data
              mountPath: /var/lib/influxdb
            - name: config
              mountPath: /etc/influxdb
