---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: monitoring
  labels:
    app: influxdb
spec:
  ports:
  - name: http
    port: 8086
  - name: admin
    port: 8083
  selector:
    app: influxdb

