apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: keystone
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: keystone
    spec:
      containers:
        - name: keystone
          image: timothyb89/keystone:0.0.1
          ports:
            - name: http
              containerPort: 5000
            - name: admin
              containerPort: 35357
---
apiVersion: v1
kind: Service
metadata:
  name: keystone
  namespace: monitoring
  labels:
    app: keystone
spec:
  type: NodePort
  ports:
    - name: http
      port: 5000
      targetPort: http
    - name: admin
      port: 35357
      targetPort: admin
  selector:
    app: keystone
