apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zookeeper
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: zookeeper:3.3
          ports:
            - name: client
              containerPort: 2181
            - name: peer
              containerPort: 2888
            - name: leader-election
              containerPort: 3888
          volumeMounts:
            - name: data
              mountPath: /data
            - name: datalog
              mountPath: /datalog
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: monitoring-zookeeper
        - name: datalog
          persistentVolumeClaim:
            claimName: monitoring-zookeeper-log
