---
- name: Install cinder
  apt: name="{{ item }}" state=present
  with_items:
    - cinder-api

- name: Minimize cinder footprint
  lineinfile: dest=/etc/cinder/cinder.conf regexp="^osapi_volume_workers" line="osapi_volume_workers = 1"
