---
apiVersion: v1
kind: ReplicationController
metadata:
  name: monasca-persister-controller
  namespace: monitoring
spec:
  replicas: 1
  selector:
    app: monasca-persister
  template:
    metadata:
      labels:
        app: monasca-persister
    spec:
      containers:
      - name: monasca-persister
        image: rbrndt/monasca-persister:latest
        ports:
        - containerPort: 8090
          name: admin
        volumeMounts:
        - name: config-volume
          mountPath: /config
      volumes:
      - name: config-volume
        configMap:
          name: monasca-persister-java-config
