- name: Install Monasca notification
  hosts: localhost
  sudo: yes
  vars:
    kafka_hosts: kafka:9092
    mysql_host: mysql
    mysql_user: notification
    mysql_password: password
    smtp_host: smtp
    zookeeper_hosts: zookeeper:2181
  roles:
    - {role: tkuhlman.monasca-notification, tags: [notification]}
