- name: Install Monasca notification
  hosts: localhost
  sudo: yes
  vars:
    kafka_hosts: kafka:9092
    mysql_host: mysql
    mysql_user: notification
    mysql_password: password
    smtp_host: localhost
    zookeeper_hosts: zookeeper:2181
  roles:
    - {role: monasca-notification, tags: [notification]}
  tasks:
    - name: Install postfix, needed by notification engine
      apt: name=postfix state=present
