- name: Install Monasca api
  hosts: localhost
  sudo: yes
  vars:
    api_region: mini-mon
    influxdb_url: http://influxdb:8086
    influxdb_user: mon_api
    influxdb_password: password
    influxdb_version: 0.8.8
    kafka_hosts: kafka:9092
    keystone_host: keystone
    keystone_auth_method: token
    keystone_admin: admin
    keystone_admin_token: ADMIN
    keystone_admin_password: admin
    mysql_host: mysql
    mysql_user: monapi
    mysql_password: password
    zookeeper_hosts: zookeeper:2181
    verify: False
  roles:
    - {role: monasca-api, tags: [api]}
