repository: monasca/client
variants:
  - tag: pike-latest
    aliases:
      - :pike-{date}-{time}
    args:
      CLIENT_BRANCH: pike-latest
      PYTHON_VERSION: '2'
      TIMESTAMP_SLUG: 20170809-155207
      CONSTRAINTS_BRANCH: pike-latest
