repository: fest/client
variants:
  - tag: pike-latest
    aliases:
      - :pike-{date}-{time}
    args:
      CLIENT_BRANCH: stable/pike
      PYTHON_VERSION: '2'
      TIMESTAMP_SLUG: pike-latest
      CONSTRAINTS_BRANCH: stable/pike
