repository: fest/api
variants:
  - tag: pike-latest
    aliases:
      - :pike-{date}-{time}
    args:
      API_BRANCH: stable/pike
      CONSTRAINTS_BRANCH: stable/pike
      TIMESTAMP_SLUG: pike-latest
