repository: fest/persister
variants:
  - tag: 2.0.0
    aliases:
      - :pike-{date}-{time}
    args:
      CONSTRAINTS_BRANCH: stable/pike
      PERSISTER_BRANCH: stable/pike
      PYTHON_VERSION: '2'
      TIMESTAMP_SLUG: 2.0.0
