repository: fest/persister
variants:
  - tag: pike-latest
    aliases:
      - :pike-{date}-{time}
    args:
      CONSTRAINTS_BRANCH: stable/pike
      PERSISTER_BRANCH: stable/pike
      PYTHON_VERSION: '2'
      TIMESTAMP_SLUG: pike-latest
 
