apiVersion: batch/v1
kind: Job
metadata:
  name: grafana-init-job
  namespace: monitoring
spec:
  template:
    metadata:
      labels:
        app: grafana-init-job
    spec:
      restartPolicy: Never
      containers:
        - name: influx-init-job
          image: monasca/grafana-init:latest
