apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
data:
  grafana.ini: |
    [paths]
    plugins = /var/lib/grafana/plugins

    [auth.basic]
    enabled = false

    [users]
    allow_sign_up = true
    allow_org_create = true

    [auth.keystone]
    enabled = true
    auth_url = http://keystone:5000
    verify_ssl_cert = false
    v3 = true
    default_domain = Default

    [log.console]
    level = trace
