apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      volumes:
        - name: grafana-config
          configMap:
            name: grafana-config
      containers:
        - name: grafana
          image: monasca/grafana:4.1.0-pre1-1.0.0
          ports:
            - name: http
              containerPort: 3000
          volumeMounts:
            - name: grafana-config
              mountPath: /etc/grafana
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  type: NodePort
  ports:
    - name: http
      port: 3000
      targetPort: http
  selector:
    app: grafana
