---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monasca-api
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: monasca-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "4888"
    spec:
      containers:
      - name: monasca-api
        image: monasca/api:master-prometheus
        imagePullPolicy: Always
        ports:
          - containerPort: 8070
            name: client
      - name: monasca-sidecar
        image: timothyb89/monasca-sidecar:1.0.0
        ports:
          - containerPort: 4888
            name: scrape
