---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monasca-api
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: monasca-api
    spec:
      containers:
      - name: monasca-api
        image: monasca/api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8070
          name: client
