---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monasca-persister
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: monasca-persister
    spec:
      containers:
      - name: monasca-persister
        image: monasca/persister:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8090
          name: admin
