- name: Install OpenStack components for use by Monasca
  hosts: localhost
  sudo: yes
  vars:
    horizon_path: /usr/share/openstack-dashboard/
    grafana_base_dir: /opt
    grafana_dest: /usr/share/openstack-dashboard/static/grafana
    keystone_admin_token: ADMIN
    keystone_url: http://localhost:35357/v3
  roles:
    - {role: keystone, tags: [keystone]}
    - {role: horizon, tags: [horizon]}
    - {role: monasca-ui, tags: [ui]}
    - {role: nova, tags: [nova]}
    - {role: glance, tags: [glance]}
    - {role: cinder, tags: [cinder]}
  tasks:
    - name: Link static dir for Monasca horizon plugin, I am not sure why this install needs this unlike others
      file: src=/usr/share/openstack-dashboard/monitoring/static/monitoring dest=/usr/share/openstack-dashboard/openstack_dashboard/static/monitoring state=link
  post_tasks:
    - name: oslo.config is getting installed via pip and the os and they conflic
      pip: name=oslo.config state=absent
