- name: Install OpenStack components for use by Monasca
  hosts: localhost
  sudo: yes
  vars:
    dashboard_path: /usr/share/openstack-dashboard/openstack_dashboard/
    grafana_base_dir: /opt
    grafana_dest: /usr/share/openstack-dashboard/static/grafana
    panel_dest_path: /usr/share/openstack-dashboard/monitoring
    keystone_admin_token: ADMIN
    keystone_url: http://localhost:35357/v3
  roles:
    - {role: keystone, tags: [keystone]}
    - {role: horizon, tags: [horizon]}
    - {role: monasca-ui, tags: [ui]}
    - {role: nova, tags: [nova]}
  tasks:
    - name: Link static dir for Monasca horizon plugin, I am not sure why this install needs this unlike others
      file: src=/usr/share/openstack-dashboard/monitoring/static/monitoring dest=/usr/share/openstack-dashboard/openstack_dashboard/static/monitoring state=link
