---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: storm-nimbus
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: storm-nimbus
    spec:
      containers:
        - name: monasca-thresh
          image: timothyb89/storm:1.0.2.4
          args: ["storm", "nimbus"]
          ports:
            - containerPort: 6627
              name: nimbus
          env:
            - name: STORM_TEMPLATE_DIR
              value: /tmpl
            - name: STORM_CONF_DIR
              value: /conf
            - name: STORM_LOCAL_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: thresh-config-volume
              mountPath: /config
            - name: storm-config-volume
              mountPath: /tmpl
            - name: data
              mountPath: /data
      volumes:
        - name: thresh-config-volume
          configMap:
            name: monasca-thresh-config
        - name: storm-config-volume
          configMap:
            name: storm-config
        - name: data
          emptyDir: {}
