- src: https://github.com/hpcloud-mon/ansible-monasca-default-alarms
  name: monasca-default-alarms
- src: tkuhlman.monasca-agent
  name: monasca-agent
- src: tkuhlman.monasca-keystone
  name: monasca-keystone
