repository: monasca/kafka
variants:
  - tag: 0.9.0.1-2.11-1.1.0
    aliases:
      - :latest
    args:
      KAFKA_VERSION: "0.9.0.1"
      SCALA_VERSION: "2.11"
  - tag: 0.9.0.1-2.11-1.0.2
    args:
      KAFKA_VERSION: "0.9.0.1"
      SCALA_VERSION: "2.11"
