---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monasca-agent-kubernetes-api
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        target: kubernetes-api
        app: monasca-agent
    spec:
      containers:
        - name: monasca-agent
          image: monasca/agent:latest
          env:
            - name: AGENT_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: AGENT_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KUBERNETES_API
              value: "true"
            - name: PROMETHEUS
              value: "true"
            - name: PROMETHEUS_DETECT_METHOD
              value: service
