---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monasca-persister
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: monasca-persister
    spec:
      containers:
      - name: monasca-persister
        image: rbrndt/monasca-persister-python:latest
        ports:
        - containerPort: 8090
          name: admin
        volumeMounts:
        - name: config-volume
          mountPath: /etc/monasca-persister
      volumes:
      - name: config-volume
        configMap:
          name: monasca-persister.config.python

