---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: monasca-agent
  namespace: monitoring
spec:
  template:
    metadata:
      labels:
        target: node
        app: monasca-agent
    spec:
      containers:
        - name: monasca-agent
          image: monasca/agent:latest
          imagePullPolicy: Always
          env:
            - name: AGENT_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: AGENT_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KUBERNETES
              value: "true"
            - name: PROMETHEUS
              value: "true"
            - name: PROMETHEUS_DETECT_METHOD
              value: pod
            - name: HOSTNAME_FROM_KUBERNETES
              value: "true"
            - name: CADVISOR
              value: "true"
          volumeMounts:
            - name: procmount
              mountPath: /host/proc
              readOnly: true
      volumes:
        - hostPath:
            path: /proc
          name: procmount
