apiVersion: batch/v1
kind: Job
metadata:
  name: monasca-thresh-submit
  namespace: monitoring
spec:
  template:
    metadata:
      labels:
        app: monasca-thresh-submit
    spec:
      restartPolicy: OnFailure
      containers:
        - name: monasca-thresh-submit
          image: rbrndt/monasca-thresh:latest
          volumeMounts:
            - name: thresh-config-volume
              mountPath: /config
          env:
            - name: NIMBUS_ADVERTISED_HOSTNAME
              value: nimbus
      volumes:
        - name: thresh-config-volume
          configMap:
            name: monasca-thresh-config
