- name: Installs influxdb
  hosts: localhost
  sudo: yes
  vars:
    influxdb:
      version: 0.8.8
      raft_port: 9090
      seed_servers: []
      replication_factor: 1
    influxdb_users:
      mon_api: password
      mon_persister: password
    influxdb_url: http://localhost:8086
    kafka_topics_enabled: false
    mysql_schema_enabled: false
    winchester_schema_enabled: false
  roles:
    - {role: influxdb, tags: [influxdb]}
    - {role: monasca-schema, tags: [schema]}
