- name: Installs influxdb
  hosts: localhost
  sudo: yes
  vars:
    influxdb:
      version: 0.8.1
      raft_port: 9090
      seed_servers: []
      replication_factor: 1
  roles:
    - {role: stympy.influxdb, tags: [influxdb]}

- name: Sets up influxdb schema
  hosts: localhost
  sudo: yes
  vars:
    influxdb_users:
      mon_api: password
      mon_persister: password
  roles:
    # the influxdb portition is tagged influxdb_schema and is all that should be run
    - {role: tkuhlman.monasca-schema, tags: [schema]}
