---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: influx
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      volumes:
        - name: config
          configMap:
            name: influxdb-1.0.0.conf
      containers:
        - name: influxdb
          image: influxdb:1.1
          ports:
            - containerPort: 8086
              name: http
            - containerPort: 8083
              name: admin
          volumeMounts:
            - name: config
              mountPath: /etc/influxdb
