---
apiVersion: v1
kind: ReplicationController
metadata:
  name: influx-controller
  namespace: monitoring
spec:
  replicas: 1
  selector:
    app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
        - name: influxdb
          image: monasca/influxdb:0.11.1
          ports:
            - containerPort: 8086
              name: http
            - containerPort: 8083
              name: admin
