- name: Install Monasca api
  hosts: localhost
  sudo: yes
  vars:
    api_region: mini-mon
    influxdb_host: influxdb
    influxdb_user: mon_api
    influxdb_password: password
    kafka_hosts: kafka:9092
    keystone_host: keystone
    keystone_admin: admin
    keystone_admin_password: password
    keystone_admin_token: ADMIN
    mysql_host: mysql
    mysql_user: monapi
    mysql_password: password
    zookeeper_hosts: zookeeper:2181
  roles:
    - {role: tkuhlman.monasca-api, tags: [api]}
